Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0c55b159cbfafe1f0
      InstanceType: t2.micro
      KeyName: mykeypair
      SecurityGroupIds:
        - sg-0123456789abcdef

  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow HTTP and SSH access
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  EIP:
    Type: AWS::EC2::EIP
    Properties:
      InstanceId: !Ref EC2Instance

  DBInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBName: mydatabase
      Engine: mysql
      MasterUsername: myusername
      MasterUserPassword: mypassword
      DBInstanceClass: db.t2.micro

Outputs:
  WebsiteURL:
    Value: !Sub "http://${EIP.PublicIp}"
